### ISSUE TITLE
Can I package this for marmalade?

### ISSUE THREAD

**Issue by nicferrier** [psanford/emacs-oauth#3]
I'd like to package your oauth module for marmalade, possibly along with my own HTTP client https://github.com/nicferrier/elnode/blob/master/elnode-client.el#L470

ELPA has an oauth2 implementation so having your oauth would make lots of sense... we could access the majority of oauth sources from Emacs then.

What do you say?

**Comment by psanford** [comment]
I give you my blessing to put this on marmalade. 

I'm not sure that anyone actually uses this library. Twittering-mode has its own implementation of oauth and I don't know of too many other packages that are active and need an oauth implementation. That being said, if anyone find this useful I'm happy for it to be on marmalade.
